apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: demo
  namespace: demo
spec:
  traffic:
  - revisionName: demo-00001
    percent: 100
  - revisionName: demo-00002
    name: uat # A named route
    percent: 0
