apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: demo
  namespace: demo
spec:
  revisionTemplate:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      container:
        image: krancour/blue-green-demo:v1.1.0
